version: '3.3'
services:
  backend:
    build: .
    container_name: pos-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://admin:n0l0g0@46.250.228.134:27017/pos?authSource=admin
      - JWT_SECRET=your-secret
