version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: pos-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://admin:n0l0g0@46.250.228.134:27017/pos?authSource=admin
      - JWT_SECRET=your-secret
    depends_on:
      - mongo

volumes:
  mongo-data:
